fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

domains:
    resource: "@DomainsBundle/Controller/"
    type:     annotation
    prefix:   /